# Generated by Django 5.2.17 on 2026-09-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PivotMindAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='PivotMind Analysis', max_length=200)),
                ('dataset_name', models.CharField(blank=True, max_length=200)),
                ('user_query', models.TextField(blank=True)),
                ('autopilot_mode', models.BooleanField(default=True)),
                ('health_score', models.FloatField(default=0.0)),
                ('health_rating', models.CharField(default='Fair', max_length=40)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('column_count', models.PositiveIntegerField(default=0)),
                ('doctor_report', models.JSONField(blank=True, default=dict)),
                ('profile_summary', models.TextField(blank=True)),
                ('hypotheses_report', models.JSONField(blank=True, default=dict)),
                ('top_hypothesis', models.JSONField(blank=True, default=dict)),
                ('viz_report', models.JSONField(blank=True, default=dict)),
                ('executive_summary', models.TextField(blank=True)),
                ('execution_time', models.FloatField(default=0.0, help_text='Total seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
