# Generated by Django 5.2.17 on 2026-09-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_pivotmindanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='pivotmindanalysis',
            name='all_visualizations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
