# Generated by Django 5.2.17 on 2026-09-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_pivotmindanalysis_all_visualizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='pivotmindanalysis',
            name='saved_file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
