# Generated by Django 5.2.17 on 2026-09-16 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_pivotmindanalysis_saved_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeattempt',
            name='agent_execution',
        ),
        migrations.RemoveField(
            model_name='challengeattempt',
            name='challenge',
        ),
        migrations.DeleteModel(
            name='ToolExecution',
        ),
        migrations.DeleteModel(
            name='AgentExecution',
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.DeleteModel(
            name='ChallengeAttempt',
        ),
    ]
